# Generated by Django 3.0.3 on 2024-04-27 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_reviews', '0002_auto_20240426_2325'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('user_level', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant_reviews.District'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_taste', models.PositiveIntegerField()),
                ('rating_decor', models.PositiveIntegerField()),
                ('rating_service', models.PositiveIntegerField()),
                ('rating_hygiene', models.PositiveIntegerField()),
                ('rating_value', models.PositiveIntegerField()),
                ('dining_method', models.CharField(max_length=200)),
                ('review_date', models.DateField(null=True)),
                ('date_of_visit', models.DateField(null=True)),
                ('spending_per_head', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('comment', models.TextField()),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant_reviews.Restaurant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant_reviews.User')),
            ],
        ),
    ]
