# Generated by Django 3.2.25 on 2024-04-28 10:51

from django.db import migrations
import django.utils.timezone
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_reviews', '0004_auto_20240427_1735'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'get_latest_by': 'modified'},
        ),
        migrations.AddField(
            model_name='review',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified'),
        ),
    ]
