# Generated by Django 3.2.25 on 2024-04-28 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_reviews', '0005_auto_20240428_1851'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={},
        ),
        migrations.RemoveField(
            model_name='review',
            name='created',
        ),
        migrations.RemoveField(
            model_name='review',
            name='modified',
        ),
    ]
