# Generated by Django 3.2.25 on 2024-04-28 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_reviews', '0007_review_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='created_at',
        ),
    ]
