# Generated by Django 3.2.25 on 2024-04-28 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_reviews', '0009_auto_20240428_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
